### ISSUE TITLE
Support background color in layout

### ISSUE THREAD

**Issue by uuttff8** [TextureCommunity/TextureSwiftSupport#21]
is it a way to support a background color method for changing color in layout, just like swiftui does?

```
List {
    Section(header: Text("First Section")) {
         Text("First Cell")
     }
     Section(header: Text("Second Section")) {
          Text("First Cell")
     }
}
.background(Color.yellow)
```

**Comment by muukii** [comment]
@uuttff8 
Thank you.

Sorry about that, I don't think we can get this currently.
Because TextureSwiftSupport's DSL can only support **Layout**. that doesn't contain modifying style and creating a node without referencing.
And I thought if we try to get this, we have to get a drastic change.

**Comment by uuttff8** [comment]
thank you, closed.
