### ISSUE TITLE
Support SPM

### ISSUE THREAD

**Issue by uuttff8** [TextureCommunity/TextureSwiftSupport#22]
supporting Swift Package Manager in 2020 is must have

**Comment by uuttff8** [comment]
also does this project support iOS < 13?

**Comment by muukii** [comment]
@uuttff8 
Thanks. I think so too.
However, I'm not sure how we could do this with Objective-C based library (Texture).
If you have any idea, could you submit the PR to get this?

**Comment by uuttff8** [comment]
hmm seems like Texture does not support SPM, so it's not possible for this project.

**Comment by AndrewSB** [comment]
I'd still like to see this project vended through SPM, assuming an app already has texture in it some other way. I'm going to try to throw up a PR
